APP_NAME = "Duplicate Killer"
APP_VERSION = "1.0.0"
APP_AUTHOR = "TRMV"

HASH_ALGORITHM = "md5"
CHUNK_SIZE = 65536

IS_PRO = False

LANGUAGES = ["en", "ru"]

STRINGS = {
    "en": {
        "app_title": "Duplicate Killer",
        "select_folder": "Select Folder",
        "start_scan": "Start Scan",
        "stop_scan": "Stop",
        "delete": "Delete Selected",
        "settings": "Settings",
        "export": "Export",
        "files_scanned": "Files scanned: {}",
        "duplicate_groups": "Duplicate groups: {}",
        "wasted_space": "Wasted space: {}",
        "name": "Name",
        "size": "Size",
        "path": "Path",
        "no_duplicates": "No duplicates found.",
        "scan_complete": "Scan complete.",
        "scanning": "Scanning...",
        "ready": "Ready",
        "confirm_delete_title": "Confirm Deletion",
        "confirm_delete_msg": "Are you sure you want to delete {} file(s) ({} wasted)?\n\nThis will send them to Recycle Bin.",
        "error": "Error",
        "warning": "Warning",
        "info": "Information",
        "close": "Close",
        "cancel": "Cancel",
        "confirm": "Confirm",
        "export_success": "Export successful: {}",
        "export_fail": "Export failed: {}",
        "select_all": "Select All Duplicates",
        "deselect_all": "Deselect All",
        "choose_folder": "Choose a folder to scan",
        "folder_not_found": "Folder not found: {}",
        "scan_error": "Scan error: {}",
        "delete_error": "Delete error: {}",
        "settings_title": "Settings",
        "theme": "Theme",
        "language": "Language",
        "excluded_folders": "Excluded Folders",
        "excluded_extensions": "Excluded Extensions",
        "add": "Add",
        "remove": "Remove",
        "save": "Save",
        "dark": "Dark",
        "light": "Light",
        "bytes": "bytes",
        "kb": "KB",
        "mb": "MB",
        "gb": "GB",
        "tb": "TB",
        "files": "files",
        "copies": "copies",
    },
    "ru": {
        "app_title": "Duplicate Killer",
        "select_folder": "Выбрать папку",
        "start_scan": "Начать поиск",
        "stop_scan": "Остановить",
        "delete": "Удалить выбранное",
        "settings": "Настройки",
        "export": "Экспорт",
        "files_scanned": "Файлов просканировано: {}",
        "duplicate_groups": "Групп дубликатов: {}",
        "wasted_space": "Занимаемое место: {}",
        "name": "Имя",
        "size": "Размер",
        "path": "Путь",
        "no_duplicates": "Дубликаты не найдены.",
        "scan_complete": "Сканирование завершено.",
        "scanning": "Сканирование...",
        "ready": "Готово",
        "confirm_delete_title": "Подтверждение удаления",
        "confirm_delete_msg": "Вы уверены, что хотите удалить {} файл(ов) ({} освободится)?\n\nФайлы будут перемещены в Корзину.",
        "error": "Ошибка",
        "warning": "Предупреждение",
        "info": "Информация",
        "close": "Закрыть",
        "cancel": "Отмена",
        "confirm": "Подтвердить",
        "export_success": "Экспорт выполнен: {}",
        "export_fail": "Ошибка экспорта: {}",
        "select_all": "Выбрать все копии",
        "deselect_all": "Снять выбор",
        "choose_folder": "Выберите папку для сканирования",
        "folder_not_found": "Папка не найдена: {}",
        "scan_error": "Ошибка сканирования: {}",
        "delete_error": "Ошибка удаления: {}",
        "settings_title": "Настройки",
        "theme": "Тема",
        "language": "Язык",
        "excluded_folders": "Исключённые папки",
        "excluded_extensions": "Исключённые расширения",
        "add": "Добавить",
        "remove": "Удалить",
        "save": "Сохранить",
        "dark": "Тёмная",
        "light": "Светлая",
        "bytes": "байт",
        "kb": "КБ",
        "mb": "МБ",
        "gb": "ГБ",
        "tb": "ТБ",
        "files": "файлов",
        "copies": "копий",
    },
}

DEFAULT_SETTINGS = {
    "theme": "dark",
    "language": "en",
    "excluded_folders": [],
    "excluded_extensions": [],
    "last_path": "",
}

SETTINGS_FILE = "settings.json"
LOG_FILE = "duplicate_killer.log"
